# Generated by Django 5.0.2 on 2024-08-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=255, null=True)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Profile_Picture', models.ImageField(default='', max_length=350, upload_to='images')),
                ('Username', models.CharField(max_length=50)),
                ('Email_Id', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Address_Line1', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Pincode', models.CharField(max_length=50)),
            ],
        ),
    ]
